name: Continuous Integration

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup | Install uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup | Install Python & Project dependencies
        run: uv sync --all-groups

      - name: Lint | Format (ruff)
        run: |
          make format
          make fix

      - name: Lint | Type check (mypy, pyright, ty)
        run: make lint

      - name: Test | Run test suite
        run: make test

      - name: Test | Run tests with coverage
        run: make test-cov

      - name: Upload | Coverage to Codecov
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
