name: CI/CD

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup UV
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Format and fix
        run: |
          make format
          make fix

      - name: Lint and type check
        run: make lint

      - name: Test with coverage
        run: make test-cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5
        with:
          files: ./coverage.xml
          flags: ${{ matrix.python-version }}
          name: Coverage (${{ matrix.python-version }})
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Clean cache
        run: uv cache prune --ci

  build:
    name: Build
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      dist_artifacts: dist
      lock_file_artifact: uv.lock

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - name: Setup release branch
        run: git checkout -B ${{ github.ref_name }}

      - name: Setup UV
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6
        with:
          enable-cache: true

      - name: Install build dependencies
        run: uv sync --group build --no-default-groups

      - name: Build package
        id: version
        env:
          GH_TOKEN: "none"
        run: uv run semantic-release -v version --no-commit --no-tag

      - name: Upload package artifacts
        if: ${{ steps.version.outputs.released == 'true' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.dist_artifacts }}
          path: ${{ format('{0}/**', env.dist_artifacts) }}
          if-no-files-found: error
          retention-days: 2

      - name: Upload lock file
        if: ${{ steps.version.outputs.released == 'true' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.lock_file_artifact }}
          path: ${{ env.lock_file_artifact }}
          if-no-files-found: error
          retention-days: 2

      - name: Clean cache
        run: uv cache prune --ci

    outputs:
      released: ${{ steps.version.outputs.released }}
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}
      dist_artifacts: ${{ env.dist_artifacts }}
      lock_file_artifact: ${{ env.lock_file_artifact }}

  e2e:
    name: E2E Tests
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.sha }}
          fetch-depth: 1

      - name: Setup UV
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Run E2E tests
        run: uv run pytest -vv tests/e2e

      - name: Clean cache
        run: uv cache prune --ci

  e2e-built:
    name: E2E Tests (Built)
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && needs.build.outputs.released == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.sha }}
          fetch-depth: 1

      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        id: artifact-download
        with:
          name: ${{ needs.build.outputs.dist_artifacts }}
          path: ./dist

      - name: Setup UV
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Install built package
        run: |
          uv pip uninstall chaturbate-events
          uv pip install dist/chaturbate_events-*.whl

      - name: Run E2E tests on built package
        run: uv run pytest -vv tests/e2e

      - name: Clean cache
        run: uv cache prune --ci

  release:
    name: Release
    needs:
      - build
      - e2e-built
    if: ${{ github.ref == 'refs/heads/main' && needs.build.outputs.released == 'true' }}

    concurrency:
      group: release-${{ github.ref_name }}
      cancel-in-progress: false

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Reset to workflow SHA
        run: git reset --hard ${{ github.sha }}

      - name: Setup UV
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6
        with:
          enable-cache: true

      - name: Install build dependencies
        run: uv sync --group build --no-default-groups

      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        id: artifact-download
        with:
          name: ${{ needs.build.outputs.dist_artifacts }}
          path: dist

      - name: Download lock file
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: ${{ needs.build.outputs.lock_file_artifact }}

      - name: Stage lock file
        run: git add uv.lock

      - name: Create release
        id: release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash .github/workflows/verify_upstream.sh
          uv run semantic-release -v --strict version --skip-build
          uv run semantic-release publish

      - name: Clean cache
        run: uv cache prune --ci

    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}
      tag: ${{ steps.release.outputs.tag }}

  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    needs:
      - release
    if: ${{ github.ref == 'refs/heads/main' && needs.release.outputs.released == 'true' && github.repository == 'MountainGod2/chaturbate-events' }}

    environment:
      name: pypi
      url: https://pypi.org/project/chaturbate-events/

    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        id: artifact-download
        with:
          name: ${{ needs.build.outputs.dist_artifacts }}
          path: .

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1
        with:
          packages-dir: dist
          print-hash: true
          verbose: true
